server {
    listen 0.0.0.0:8022

    location / {
        root ./site_tester/ 
        allow_methods GET
    }

    location /put_test/ {
        allow_methods PUT
        root ./site_tester/put_test/
    }

    location ~ \.bla$ {
        allow_methods POST
        cgi_pass ./site_tester/ubuntu_cgi_tester 
    }

    location /post_body {
        allow_methods POST
        client_max_body_size 100
    }

    location /directory/ {
        root ./site_tester/directory/
        allow_methods GET
        index youpi.bad_extension
    }
}

